name: Main Release

on:
  create:
    tags:
      - v[0-9]**

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: test
        run: |
          cp CI/ESS/docker-compose.gitlab.yaml docker-compose.yaml
          docker-compose down --remove-orphans
          docker-compose pull
          docker-compose up --build --exit-code-from scicat-backend
          docker-compose down

  new-main-release:
    name: New main release on the main branch and docker image
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checking release
        run: echo "Releasing version ${{ github.ref_name }}"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: scicatproject/backend:${{ github.ref_name }},scicatproject/backend:stable
